export const ActionTypes = {
    CHANGE_LANGUAGE: '[APP] CHANGE LANGUAGE',
    SHOW_TOAST : '[APP] SHOW TOAST',
    APP_LOADING : '[APP] LOADING',
    STORE_USER_PROFILE : '[USER] STORE USER PROFILE'
}